# k:(空格)v：表示一对键值对（空格必须有),属性和值也是大小写敏感
#person:
##  lastName: hello
#  last-name: hello
#  age: 18
#  boss: false
#  birth: 2017/12/12
#  maps: {k1: v1,k2: 12}
#  lists:
#    - lisi
#    - zhaoliu
#  dog:
#    name: 小狗
#    age: 12

server:
  port: 8081
spring:
  profiles:
    active: prod  #激活哪个环境
---
server:
  port: 8083
spring:
  profiles: dev   #指定属于dev环境
---
server:
  port: 8084
spring:
  profiles: prod  #指定属于prod环境
---


spring:
  messages:
    encoding: utf-8
    basename: i18n/messages
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: zuoqiang
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

  mybatis-plus:
    type-aliases-package: com.zuoqiang.learn.springboot.entity
    mapper-locations: classpath:mapper/*/*.xml
    configuration:
      jdbc-type-for-null: null
    global-config:
      banner: false
      db-config:
        select-strategy: not_empty